### ISSUE TITLE
在编译opencv-mobile-4.9.0版本添加imgcodecs模块出现编译问题

### ISSUE THREAD

**Issue by kylin33** [nihui/opencv-mobile#113]
opencv-mobile/opencv-mobile-4.9.0/modules/imgcodecs/src/loadsave.cpp:789:36: error: 'const class cv::_InputArray' has no member named 'isUMatVector'; did you mean 'isMatVector'?
     if (_img.isMatVector() || _img.isUMatVector())
                                    ^~~~~~~~~~~~
                                    isMatVector

检查发现_InputArray类中没有了.isUMatVector()函数,希望能够解决

**Comment by kylin33** [comment]
我目前屏蔽掉imgcodes中涉及UMat相关代码能完成编译。

**Comment by ilya-sha** [comment]
@kylin33 can you please share your changes
