### ISSUE TITLE
Android 集成 .a 编译报错

### ISSUE THREAD

**Issue by vscoder-mas** [nihui/opencv-mobile#125]
```c++
cv::Mat srcImage = cv::imread(_picPath);
cv::Mat dstImage;
cv::resize(srcImage, dstImage, cv::Size(srcImage.cols * factor, srcImage.rows * factor), 0,
0, cv::INTER_NEAREST);
cv::imwrite(_outPath, dstImage);
```
就想使用 opencv 最基本的 resize 功能，将所有 .a 都加到 CMakeLists.txt 中，编译不过。但是用官网的 libopencv_java4.so 就没问题。但是 libopencv_java4.so 20M，太大了。有没有什么办法能使so小点，或只引入某个 .a
有没有遇到相同问题的朋友，帮忙解答一下~

**Comment by nihui** [comment]
报错信息呢？

**Comment by vscoder-mas** [comment]
> 报错信息呢？
resolved : https://github.com/nihui/opencv-mobile/issues/47
