### ISSUE TITLE
cv::putText for non-ascii characters

### ISSUE THREAD

**Issue by nihui** [nihui/opencv-mobile#127]

**Comment by erquren** [comment]
love from china

**Comment by nihui** [comment]
implemented since https://github.com/nihui/opencv-mobile/commit/b71dcfe02f8d5be40711bb42240cd8bad45885a1

**Comment by yangy996** [comment]
大佬，这个怎么用？为什么这样写，图片上没任何文字呢？
cv::putText(origin, "你是？", cv::Point(5, 5), cv::FONT_HERSHEY_SCRIPT_SIMPLEX, 1, cv::Scalar(0, 0, 255), 2, cv::LINE_AA);

**Comment by nihui** [comment]
> 大佬，这个怎么用？为什么这样写，图片上没任何文字呢？ cv::putText(origin, "你是？", cv::Point(5, 5), cv::FONT_HERSHEY_SCRIPT_SIMPLEX, 1, cv::Scalar(0, 0, 255), 2, cv::LINE_AA);

https://zhuanlan.zhihu.com/p/712558630

**Comment by yangy996** [comment]
大佬，这么做的话，那只能显示特定的汉字？如果文字不是固定的，那需要把常用汉字都做成头文件？
