### ISSUE TITLE
android版本调用imread时链接时报错

### ISSUE THREAD

**Issue by chinesesoft8** [nihui/opencv-mobile#152]
ibopencv_video.a  /work/mnn/opencv-mobile-4.10.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_core.a -fopenmp -static-openmp -ldl -lm -llog -latomic -lm 
ld.lld: error: undefined symbol: cv::display_fb::open()
>>> referenced by highgui.cpp
>>>               highgui.cpp.o:(cv::imshow(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, cv::_InputArray const&)) in archive /home/liujt/work/mnn/opencv-mobile-4.10.0-android/sdk/native/staticlibs/arm64-v8a/libopencv_highgui.a

ld.lld: error: undefined symbol: cv::display_fb::get_width() const
想开发一个sdk供android和ios公用，把读取文件放在sdk里头，编译时报错

**Comment by chinesesoft8** [comment]
重新编译android库，去掉imshow函数已解决。

**Comment by vinayhvaghamshi** [comment]
Found that imshow is not natively supported on Android platforms. Instead, for Android, some alternative ways for use cv::imwrite to 1. save and display media file

**Comment by nihui** [comment]
will be fixed in the next release
