### ISSUE TITLE
android api 22 version of opencv

### ISSUE THREAD

**Issue by MyraBaba** [nihui/opencv-mobile#19]
hi,

Is there android api 22 version of the prebuild opencv ?

best

**Comment by 596030631** [comment]
hi,

Is there android api 23 version of the prebuild opencv ?

best

**Comment by hungnvk54** [comment]
Hi all, Do you have any prebuild version for lower API 24?

**Comment by nihui** [comment]
https://github.com/nihui/opencv-mobile/pull/74

**Comment by nihui** [comment]
resolved since https://github.com/nihui/opencv-mobile/commit/09f5a1cd23351260ede388cfe4a5d36c6bfe8655
