### ISSUE TITLE
Need guidence on how to build opencv-mobile

### ISSUE THREAD

**Issue by CyCle1024** [nihui/opencv-mobile#4]
It's a very useful repo!!! I have a suggestion that owners can release a guide on how to build opencv-mobile library on target platform with this repo and opencv official repo. Users can use this guide to do more custom changes and get a smaller package.

**Comment by zchrissirhcz** [comment]
For more customization, people can refer to OpenCV official documentation: https://docs.opencv.org/4.5.0/db/d05/tutorial_config_reference.html

**Comment by bjheweihua** [comment]
how to build opencv2.framework with opencv+opencv_contrib and get a smaller package.

**Comment by mczhao1977** [comment]
Wonderful project! I can successfully build a customized OpenCV 4.5.4 with Emscripten SDK according to the instructions provided in "How-to-build your custom package". Only one minor problem:
I apply the no-rtti patch but can't find -fno-rtti compiling option added to the C or CXX compiler flags. Do I need manually add this compiling option to each OpenCV target?
Thanks!

**Comment by zchrissirhcz** [comment]
> Wonderful project! I can successfully build a customized OpenCV 4.5.4 with Emscripten SDK according to the instructions provided in "How-to-build your custom package". Only one minor problem: I apply the no-rtti patch but can't find -fno-rtti compiling option added to the C or CXX compiler flags. Do I need manually add this compiling option to each OpenCV target? Thanks!

Those patches remove rtti and exception related code. ` -fno-rtti ` and `-fno-exceptions` are specified when calling cmake.
See the github action configure file for details: https://github.com/nihui/opencv-mobile/blob/master/.github/workflows/release.yml

**Comment by mczhao1977** [comment]
Hi zchrissirhcz, thanks for quick answer. I tried it and it works fine.
Another question: If I want to include the module calib3d (and its dependency flann), do I need manually remove the rtti and exceptions related code? Thanks!

**Comment by zchrissirhcz** [comment]
> Hi zchrissirhcz, thanks for quick answer. I tried it and it works fine. Another question: If I want to include the module calib3d (and its dependency flann), do I need manually remove the rtti and exceptions related code? Thanks!

I didn't try using calib3d in opencv-mobile. I think you may try: compile with the official OpenCV's calib3d source code (same version as other modules, say, 4.5.5), with `-fno-rtti` and `-fno-exceptions` passed to cmake, if compler/linker gives error then modify related code, just like the provided patches do (e.g. `opencv-4.5.4-no-rtti.patch`). That it, manually remove some code then compile, until linking error.

**Comment by nihui** [comment]
updated guide
https://github.com/nihui/opencv-mobile#how-to-build-your-custom-package
