### ISSUE TITLE
zip warning: name not matched install

### ISSUE THREAD

**Issue by RobinFarmer** [nihui/opencv-mobile#43]
While trying to make my own custom package following the instructions and running the last command `zip -r -9 opencv-mobile-4.6.0.zip install` I get: 

```
zip warning: name not matched: install

zip error: Nothing to do! (try: zip -r -9 opencv-mobile-4.6.0.zip . -i install)
```

I have not been able to get it to run also trying the suggested command that was in the error.

(the reason I want to make my own custom package is because the iOS opencv.framework does not include the arm64 slice for simulators which I wanted to add myself.)

**Comment by jonibim** [comment]
Before the `zip` command you need to also do the following after running the `cmake` command
```
make
make install
```
This should create an `install` folder within the `build` folder
