### ISSUE TITLE
Error: ld: error: undefined symbol: omp_get_max_threads

### ISSUE THREAD

**Issue by taiji1985** [nihui/opencv-mobile#47]
ERROR Messgage: 

ld: error: undefined symbol: omp_get_max_threads
>>> referenced by parallel.cpp
>>>               parallel.cpp.o:(_GLOBAL__sub_I_parallel.cpp) in archive F:/work/TestOpenCVMobile/app/main/jni/opencv-mobile-4.6.0-android/sdk/native/staticlibs/arm64-v8abopencv_core.a

I do a opencv-mobile demo followed the instruction of 

https://github.com/nihui/opencv-mobile#usage-android

but got above error . 

I think it may loss the dependency of openmp . I don't know if it is a bug .

---------------
I add ncnn and   pass the build , may due to the openmp is contained by ncnn .

**Comment by laxnpander** [comment]
Compile with 
```c
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fopenmp -static-openmp")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fopenmp -static-openmp")
```

**Comment by taiji1985** [comment]
Thanks
