### ISSUE TITLE
'opencv2/opencv.hpp' file not found

### ISSUE THREAD

**Issue by nil-known** [nihui/opencv-mobile#5]
Xcode Version 12.4 
Framework source in use : https://opencv.org/releases/
It works correctly

I wanted to use a lightweight framework, so I tried to replace it.
- opencv-mobile-3.4.13-ios-bitcode
- opencv-mobile-4.5.1-ios-bitcode 

error : 'opencv2/opencv.hpp' file not found

No settings have changed from working correctly. Just changed the framework

**Comment by nihui** [comment]
You need to set the include path properly
opencv2/opencv.hpp is in opencv2.framework/Headers

**Comment by nihui** [comment]
fixed in latest packed, please update and try again :)
