### ISSUE TITLE
build my custom package,how to build opencv2.framwork?please

### ISSUE THREAD

**Issue by yangy996** [nihui/opencv-mobile#52]

**Comment by niqt** [comment]
For OSX or iOS?

**Comment by yangy996** [comment]
> For OSX or iOS?

ios

**Comment by niqt** [comment]
I'm trying to copy the instructions from here https://github.com/nihui/opencv-mobile/blob/master/.github/workflows/release.yml but not successful at the moment.
With this it's build for x64...
cmake -DCMAKE_TOOLCHAIN_FILE=../../toolchains/ios.toolchain.cmake -DPLATFORM=OS -DARCHS="arm64" \
            -DDEPLOYMENT_TARGET=$IOS_DEPLOYMENT_TARGET -DENABLE_BITCODE=$ENABLE_BITCODE -DENABLE_ARC=$ENABLE_ARC -DENABLE_VISIBILITY=$ENABLE_VISIBILITY \
            -DCMAKE_C_FLAGS="frtti" -DCMAKE_CXX_FLAGS="-frtti " \
            -DCMAKE_INSTALL_PREFIX=install -DCMAKE_BUILD_TYPE=Release `cat ../../opencv4_cmake_options.txt` -DBUILD_opencv_world=ON -DOPENCV_DISABLE_FILESYSTEM_SUPPORT=ON ..

**Comment by nihui** [comment]
refer to
https://github.com/nihui/opencv-mobile/blob/dd6063730d76daa9ae3d2f41da515e48554245e3/.github/workflows/release.yml#L302
