### ISSUE TITLE
putText中文乱码 求助

### ISSUE THREAD

**Issue by yaya2212** [nihui/opencv-mobile#69]
博主帮忙看看  现在用[opencv-mobile-4.8.1-android.zip]这个版本，cv::putText设置中文乱码 怎么解决呢

**Comment by nihui** [comment]
putText 本来就不支持中文的，得用 freetype 或者更上层的 api 绘制

**Comment by yaya2212** [comment]
感谢回答
我想继续问一下，freetype是需要重新编译opencv嘛  其它api有哪些呢

**Comment by nihui** [comment]
https://github.com/nihui/opencv-mobile/issues/127
