### ISSUE TITLE
编译Android 32位so报错

### ISSUE THREAD

**Issue by caiyonglong** [nihui/opencv-mobile#71]
4.6.0 编译32位正常
升级到4.8.1之后，编译32位打包失败

错误日志：
opencv-mobile-4.8.1-android/sdk/native/staticlibs/armeabi-v7a/libopencv_core.a(copy.cpp.o):copy.cpp:function cv::scalarToRawData(cv::Scalar_<double> const&, void*, int, int): error: undefined reference to '__aeabi_d2h'

**Comment by nihui** [comment]
建议升级 android ndk 版本到 r25

**Comment by yangy996** [comment]
> 建议升级 android ndk 版本到 r25

请问下，如何能在r21上编译通过，我其他的包用的r21的

**Comment by yangy996** [comment]
> 建议升级 android ndk 版本到 r25

大佬，我把android ndk用r25编译后，还是会出现这个问题，但直接下载你编译好的Android包就没这个错误
