### ISSUE TITLE
为什么我编译出来的.a文件那么大？

### ISSUE THREAD

**Issue by yangy996** [nihui/opencv-mobile#80]
![image](https://github.com/nihui/opencv-mobile/assets/15188456/4a5ad8d5-910a-460f-b3a8-a2f7994908f4)

**Comment by zihaomu** [comment]
![image](https://github.com/nihui/opencv-mobile/assets/16487352/a4ffd86d-e1eb-474d-8843-c76567f51a5f)

同问，左边静态库和动态库都是我编出来的，右边是仓库release下载的。
ndk版本：21.2.6472646

**Comment by yangy996** [comment]
> ![image](https://private-user-images.githubusercontent.com/16487352/292827361-a4ffd86d-e1eb-474d-8843-c76567f51a5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM1ODEwNDgsIm5iZiI6MTcwMzU4MDc0OCwicGF0aCI6Ii8xNjQ4NzM1Mi8yOTI4MjczNjEtYTRmZmQ4NmQtZTFlYi00NzRkLTg4NDMtYzc2NTY3ZjUxYTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI2VDA4NTIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzOGYwOWU2OGJlYjVlMTNkNzc5MDVjNzFhN2NlMzNlZjViOWYyNDk4MmFjNjFlMTEzOWY4NDg0MzhmOTRmODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7fvok_WaL9s0rkzdskV2CWQWw5_aB0jhvCpnzxSoFGg)
> 
> 同问，左边静态库和动态库都是我编出来的，右边是仓库release下载的。 ndk版本：21.2.6472646
> 
> @nihui 求大佬解答一下

找到问题了，yml里有行代码我没注意： run: sed -i -e '/^  -g$/d' $ANDROID_NDK_LATEST_HOME/build/cmake/android-legacy.toolchain.cmake
是删除-g参数的，这个参数会导致编译出来的包非常大。

**Comment by zihaomu** [comment]
牛的
