### ISSUE TITLE
opencv_mobile_licheerv_nano 打不开摄像头

### ISSUE THREAD

**Issue by kekxv** [nihui/opencv-mobile#88]
<img width="500" alt="image" src="https://github.com/nihui/opencv-mobile/assets/15551108/3fcf27ac-7f80-42d5-90ac-22e612b53a11">

**Comment by nihui** [comment]
zip包更新啦！请再试试哟～

**Comment by kekxv** [comment]
确实可以了。
有几个注意事项：
> 目前不能加上 `-static` 参数
> 如果出现 `-sh: 程序名: not found`，可以考虑执行:
>> ```shell
>> ln -s /usr/lib64v0p7_xthead/lp64d/libc.so /lib/ld-musl-riscv64xthead.so.1
>> ln -s /usr/lib64v0p7_xthead/lp64d/libc.so /lib/ld.so.1
 >> ```

![image](https://github.com/nihui/opencv-mobile/assets/15551108/e7f1d0b2-723d-4630-bc00-bd79ec485efa)
