### ISSUE TITLE
希望作者公开各平台和各配置的编译脚本

### ISSUE THREAD

**Issue by huanghone** [nihui/opencv-mobile#97]
我在webassembly 平台上总是出现很多错误。看输出和SIMD相关，如何禁止 SIMD? 为避免这种无意义的重复性劳动，希望作者公开各平台和各配置的编译脚本。我看很多 ISSUE 都与编译相关，我也碰到了在多个平台的编译链接问题。麻烦作者公布编译脚本

**Comment by nihui** [comment]
编译脚本就在 github action 上有

https://github.com/nihui/opencv-mobile/blob/991bc4016aa7d02b7083cb392f7036ca3e4076ea/.github/workflows/release.yml#L922

**Comment by nihui** [comment]
另外，首页的 webassembly 包里面包含4种配置，其中basic就是无simd无thread

**Comment by huanghone** [comment]
谢谢
