### ISSUE TITLE
milkv duo使用opencv出现this device is not whitelisted for jpeg decoder cvi这个问题

### ISSUE THREAD

**Issue by Welpe1** [nihui/opencv-mobile#99]
使用的板子是milkv duo(64MB)版本的，直接下载的官方镜像系统
安装opencv-mobile后运行出现如下问题
this device is not whitelisted for jpeg decoder cvi
this device is not whitelisted for jpeg decoder cvi
this device is not whitelisted for jpeg decoder cvi
this device is not whitelisted for jpeg encoder rkmpp

但是我看了milkv duo是在白名单里面的，不知道该如何解决

**Comment by Welpe1** [comment]
大佬求助

**Comment by nihui** [comment]
should be fixed in https://github.com/nihui/opencv-mobile/commit/b79de2e2e224ce8ffafa5877ac6bc022844d84f3

**Comment by nihui** [comment]
更新最新的 v26 应该ok了
